# See https://juju.is/docs/config for guidance.

options:
  test-observer-api-base-uri:
    description: The base URI for the API. This is used to generate the links to the API in the frontend.
    default: "http://localhost:30000"
    type: string
